### ISSUE TITLE
rust-cardano-crypto is used in react-nativce

### ISSUE THREAD

**Issue by BenLakes** [input-output-hk/js-cardano-wasm#35]
The RN project cannot run after the rust-cardano-crypto is loaded 

![2018-10-16 7 16 21](https://user-images.githubusercontent.com/15206046/47012963-2dd4c680-d178-11e8-9b0f-6c2f43635fc5.png)
![2018-10-16 7 16 03](https://user-images.githubusercontent.com/15206046/47012977-35946b00-d178-11e8-8d26-eee5526234d8.png)
Did I miss something？

**Comment by vincenthz** [comment]
I don't think wasm is supported on iOS and android yet, which make it using react-native difficult at the moment

**Comment by nicarq** [comment]
@BenLakes you shouldn’t use the wasm library in iOS and Android. WebAssembly is not supported in iOS and the compatibility in Android differs depending on the OS version.

If you still want to try it out, you should change the default package manager for `Haul`. It doesn’t load because the size of the wasm file is too big.

**Comment by nicarq** [comment]
@BenLakes in Emurgo we will release a `react-native` library that uses cardano-rust. If you want I can ping you here when it’s ready. it should be this or next week.

**Comment by BenLakes** [comment]
@nicarq  Thank you. We are now anxious to use this library in the react native project. Please inform me immediately if you are ready.

**Comment by nicarq** [comment]
@BenLakes https://github.com/Emurgo/react-native-cardano enjoy! :)

**Comment by BenLakes** [comment]
@nicarq  Thank you
